### ISSUE TITLE
run_cmd_over_tor lacking examples

### ISSUE THREAD

**Issue by meme-lord** [NullHypothesis/exitmap#51]
So I was making a module that uses the openssl command as it was a lot more complicated to do it in just python. I was just using subprocess and run_python_over_tor until I realized it wasn't actually running the command over tor so I went to use run_cmd_over_tor.
It hasn't been used in any of the other modules or anything I could find on google so I spent some time reading it and here is a simple module for testing I came up with:

```
import logging
log = logging.getLogger(__name__)

def print_callback(input,proc_kill):
    log.info('Command Output: ' + input)
def probe(exit_desc, run_python_over_tor, run_cmd_over_tor, **kwargs):
    run_cmd_over_tor.execute(['curl','-s','https://wtfismyip.com/text'],output_callback=print_callback)
```

The only output I could get with it (even when the command was changed to something like pwd):

`2016-08-28 00:37:10,903 modules.test [INFO] Command Output: [Aug 28 00:37:10] DEBUG torsocks[18470]: Logging subsytem initialized. Level 5, file (null), time 1 (in init_logging() at torsocks.c:286)`
I would just like to be able to get all the output after the command completes.
Any help would be appreciated :)

**Comment by NullHypothesis** [comment]
You need a custom version of torsocks for this to work because exitmap relies on torsocks's source port to figure out what stream to attach it to. A long time ago, I forked torsocks and added the patch:
https://github.com/NullHypothesis/torsocks/commit/e8b3fe64a5b2c324086a16615be38736addb94f9

Torsocks's maintainer also mentioned that he's interested in merging this patch, but that might take a while. Sorry that there's no better way at the moment.

I'll keep this ticket open for now because I should add some information on this, so the next person won't have to spend as much time as you did.

**Comment by meme-lord** [comment]
Alright I removed the version of torsocks I had and compiled yours.
```
git clone -b print_source https://github.com/NullHypothesis/torsocks.git
cd torsocks
./autogen.sh
./configure
make
make check
sudo make install
```
I did have compile errors relating to LIBC_NAME but I just manually put it in.
One of the test cases test_dns uses sergii.torproject.org which doesnt exist anymore but I guess these two problems wouldn't happen if it was on the current version of torsocks.

To get the output working properly I had to change the torsocks log level in commad.py from 5 to 1.
`os.environ["TORSOCKS_LOG_LEVEL"] = "1"`

Now I can do commands like pwd and whatnot and get the output, problem is can't seem to get the same result from curl.
Using this:
`run_cmd_over_tor.execute(['curl','-s','https://check.torproject.org/api/ip'],output_callback=print_callback)`

I get no output which is weird cos
`torsocks curl https://check.torproject.org/api/ip` 
works just fine. Suggestions?

**Comment by NullHypothesis** [comment]
> To get the output working properly I had to change the torsocks log level in commad.py from 5 to 1.
os.environ["TORSOCKS_LOG_LEVEL"] = "1"

Perhaps that's the issue. If I remember correctly, it's set to 5 so that exitmap can see the debug log message that my torsocks patch triggers. If that log message does not show up on stdout, it won't work.

Apart from that, I'm not sure what could be the issue. In a first step, I would make sure that the patch applied correctly. You should now be able to see the debug log messages of the form "Connection on fd %d originating from %s:%u".

**Comment by meme-lord** [comment]
I found the problem, my callback function has to return True to continue getting output otherwise it just prints the first line of output.

**Comment by NullHypothesis** [comment]
Closing because meme-lord managed to fix the issue.
